# Generated by Django 5.2.15 on 2026-06-18 14:59

import django.db.models.deletion
import xhamia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=100, verbose_name='Emri i Kategorisë')),
                ('pershkrimi', models.TextField(blank=True, verbose_name='Përshkrimi')),
                ('shuma_vjetore', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('shuma_6mujore', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shuma_3mujore', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shuma_mujore', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('është_aktiv', models.BooleanField(default=True)),
                ('renditja', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoritë',
                'ordering': ['renditja', 'emri'],
            },
        ),
        migrations.CreateModel(
            name='PagesaFondi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_fatures', models.CharField(default=xhamia.models.gjenero_nr_fature_fondi, max_length=20, unique=True, verbose_name='Nr. Faturës')),
                ('emri_donatorit', models.CharField(max_length=100, verbose_name='Emri')),
                ('mbiemri_donatorit', models.CharField(max_length=100, verbose_name='Mbiemri')),
                ('email_donatorit', models.EmailField(blank=True, max_length=254, verbose_name='Email Donatorit')),
                ('nr_telefoni', models.CharField(blank=True, max_length=20, verbose_name='Nr. Telefoni')),
                ('shuma', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shuma (€)')),
                ('data_pageses', models.DateField(verbose_name='Data e Pagesës')),
                ('arsyeja', models.CharField(blank=True, max_length=300, verbose_name='Arsyeja / Qëllimi')),
                ('shenime', models.TextField(blank=True, verbose_name='Shënime')),
                ('data_regjistrimit', models.DateTimeField(auto_now_add=True)),
                ('arktar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagesat_fondit', to=settings.AUTH_USER_MODEL, verbose_name='Arktar')),
            ],
            options={
                'verbose_name': 'Pagesë Fondi',
                'verbose_name_plural': 'Pagesat Fondit',
                'ordering': ['-data_pageses'],
            },
        ),
        migrations.CreateModel(
            name='ProfilStafi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_telefoni', models.CharField(blank=True, max_length=20)),
                ('pozita', models.CharField(blank=True, max_length=100, verbose_name='Pozita në Xhami')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrator'), ('STAF', 'Staf')], default='STAF', max_length=10)),
                ('mund_regjistrojë_pagesa', models.BooleanField(default=False, verbose_name='Mund të regjistrojë pagesa')),
                ('merr_email_pagese', models.BooleanField(default=True, verbose_name='Merr email për çdo pagesë')),
                ('është_aktiv', models.BooleanField(default=True)),
                ('data_shtimit', models.DateTimeField(auto_now_add=True)),
                ('shtuar_nga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stafi_shtuar', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Stafi',
                'verbose_name_plural': 'Stafi',
            },
        ),
        migrations.CreateModel(
            name='Shtepia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_shtepise', models.CharField(max_length=4, unique=True, verbose_name='Nr. Shtëpisë')),
                ('emri_kryefamiljarit', models.CharField(max_length=100, verbose_name='Emri')),
                ('mbiemri_kryefamiljarit', models.CharField(max_length=100, verbose_name='Mbiemri')),
                ('nr_antareve_familjes', models.PositiveSmallIntegerField(default=1, verbose_name='Nr. Anëtarëve')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nr_telefoni_kryesor', models.CharField(blank=True, max_length=20, verbose_name='Nr. Telefoni Kryesor')),
                ('nr_telefoni_sporadik', models.CharField(blank=True, max_length=20, verbose_name='Nr. Telefoni Sporadik')),
                ('kontakt_sporadik_emri', models.CharField(blank=True, max_length=200, verbose_name='Kontakt Sporadik (Emri)')),
                ('kontakt_sporadik_email', models.EmailField(blank=True, max_length=254, verbose_name='Kontakt Sporadik (Email)')),
                ('kontakt_sporadik_telefoni', models.CharField(blank=True, max_length=20, verbose_name='Kontakt Sporadik (Tel.)')),
                ('shenime', models.TextField(blank=True, verbose_name='Shënime')),
                ('është_aktiv', models.BooleanField(default=True)),
                ('data_regjistrimit', models.DateTimeField(auto_now_add=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xhamia.kategoria', verbose_name='Kategoria e Pagesës')),
                ('regjistruar_nga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shtepite_regjistruara', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shtëpi',
                'verbose_name_plural': 'Shtëpitë',
                'ordering': ['nr_shtepise'],
            },
        ),
        migrations.CreateModel(
            name='PagesaAntaresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_fatures', models.CharField(default=xhamia.models.gjenero_nr_fature_antaresi, max_length=20, unique=True, verbose_name='Nr. Faturës')),
                ('shuma_paguar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Shuma (€)')),
                ('periudha', models.CharField(choices=[('VJETORE', 'Vjetore'), ('6MUJORE', '6-Mujore'), ('3MUJORE', '3-Mujore'), ('MUJORE', 'Mujore')], default='VJETORE', max_length=10)),
                ('viti', models.PositiveSmallIntegerField(default=2026, verbose_name='Viti')),
                ('muaji_fillimit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Muaji Fillimit')),
                ('muaji_mbarimit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Muaji Mbarimit')),
                ('data_pageses', models.DateField(verbose_name='Data e Pagesës')),
                ('shenime', models.TextField(blank=True, verbose_name='Shënime')),
                ('data_regjistrimit', models.DateTimeField(auto_now_add=True)),
                ('arktar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagesat_antaresise', to=settings.AUTH_USER_MODEL, verbose_name='Arktar')),
                ('kategoria_pageses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xhamia.kategoria', verbose_name='Kategoria')),
                ('shtepia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagesat', to='xhamia.shtepia', verbose_name='Shtëpia')),
            ],
            options={
                'verbose_name': 'Pagesë Antarësia',
                'verbose_name_plural': 'Pagesat Antarësia',
                'ordering': ['-data_pageses'],
            },
        ),
    ]
