# Generated by Django 5.2.15 on 2026-06-22 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xhamia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilShtepi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_krijimit', models.DateTimeField(auto_now_add=True)),
                ('krijuar_nga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llogarite_shtepive_krijuara', to=settings.AUTH_USER_MODEL)),
                ('shtepia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llogaria', to='xhamia.shtepia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profili_shtepi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Llogari Shtëpie',
                'verbose_name_plural': 'Llogaritë e Shtëpive',
            },
        ),
    ]
