# Generated by Django 5.2.15 on 2026-06-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xhamia', '0002_profilshtepi'),
    ]

    operations = [
        migrations.AddField(
            model_name='shtepia',
            name='viti_fillimit_antaresise',
            field=models.PositiveSmallIntegerField(default=2026, verbose_name='Antarësia Aktive nga Viti'),
        ),
    ]
