# Generated by Django 5.2.15 on 2026-06-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xhamia', '0003_shtepia_viti_fillimit_antaresise'),
    ]

    operations = [
        migrations.AddField(
            model_name='shtepia',
            name='paguar_deri_viti',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Paguar Deri Viti (Historik)'),
        ),
    ]
