# Generated by Django 5.2.15 on 2026-06-25 13:35

import django.db.models.deletion
import xhamia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xhamia', '0004_paguar_deri_viti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesaantaresia',
            name='kursi_denar',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Kursi EUR/MKD'),
        ),
        migrations.AddField(
            model_name='pagesaantaresia',
            name='shuma_mkd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Shuma (MKD)'),
        ),
        migrations.AddField(
            model_name='pagesafondi',
            name='kursi_denar',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Kursi EUR/MKD'),
        ),
        migrations.AddField(
            model_name='pagesafondi',
            name='shuma_mkd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Shuma (MKD)'),
        ),
        migrations.CreateModel(
            name='Harxhimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_fatures', models.CharField(default=xhamia.models.gjenero_nr_fature_harxhim, max_length=25, unique=True, verbose_name='Nr. Dokumentit')),
                ('lloji', models.CharField(choices=[('RROGE', 'Rroge Stafi'), ('MIREMBAJTJE', 'Mirëmbajtje'), ('RRYME', 'Rrymë Elektrike'), ('UJI', 'Ujë'), ('NXEMJE', 'Nxemje / Naftë'), ('INTERNET', 'Internet'), ('TJETER', 'Tjetër')], max_length=20, verbose_name='Lloji')),
                ('burimi', models.CharField(choices=[('ANTARESIA', 'Antarësia (Rrogat)'), ('FONDI', 'Fondi i Xhamisë')], default='FONDI', max_length=20, verbose_name='Buxheti')),
                ('pershkrimi', models.TextField(blank=True, verbose_name='Përshkrimi')),
                ('shuma_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shuma (€)')),
                ('shuma_mkd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Shuma (MKD)')),
                ('kursi_denar', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Kursi EUR/MKD')),
                ('muaji', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Muaji')),
                ('viti', models.PositiveSmallIntegerField(verbose_name='Viti')),
                ('data_pageses', models.DateField(verbose_name='Data')),
                ('data_regjistrimit', models.DateTimeField(auto_now_add=True)),
                ('arktar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harxhimet_regjistruara', to=settings.AUTH_USER_MODEL, verbose_name='Regjistruar nga')),
                ('stafi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rrogat_e_marra', to=settings.AUTH_USER_MODEL, verbose_name='Stafi (rroge)')),
            ],
            options={
                'verbose_name': 'Harxhim',
                'verbose_name_plural': 'Harxhimet',
                'ordering': ['-data_pageses'],
            },
        ),
    ]
