# Generated by Django 5.2.15 on 2026-09-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xhamia", "0005_harxhimi_mkd_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilstafi",
            name="email_njoftimesh",
            field=models.EmailField(
                blank=True,
                help_text="Nëse plotësohet, njoftimet e pagesave dërgohen këtu në vend të emailit të llogarisë.",
                max_length=254,
                verbose_name="Email zyrtar për njoftime",
            ),
        ),
    ]
