# Generated by Django 5.2.15 on 2026-09-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("xhamia", "0006_profilstafi_email_njoftimesh"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilstafi",
            name="email_njoftimesh",
        ),
    ]
